"use client";
import { FormEvent, use, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Person={user_id:string;display_name:string;role:string;avatar_url:string|null};
type Child={student_id:string;student_name:string};
export default function ReportUserPage({params}:{params:Promise<{userId:string}>}){
 const {userId}=use(params); const router=useRouter(); const supabase=useMemo(()=>createClient(),[]);
 const [person,setPerson]=useState<Person|null>(null); const [role,setRole]=useState(""); const [children,setChildren]=useState<Child[]>([]);
 const [reason,setReason]=useState("harassment"); const [details,setDetails]=useState(""); const [childId,setChildId]=useState(""); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const [{data:p},{data:me}]=await Promise.all([supabase.rpc("get_reportable_user",{p_user_id:userId}),supabase.from("profiles").select("role").eq("id",user.id).single()]); setPerson((p?.[0]??null) as Person|null); setRole(me?.role??""); if(me?.role==="parent"){const {data:c}=await supabase.rpc("get_my_children"); setChildren((c??[]) as Child[]);} })();},[supabase,userId]);
 async function submit(e:FormEvent){e.preventDefault();setMessage("");setSaving(true);const {error}=await supabase.rpc("submit_user_report",{p_reported_user_id:userId,p_reason:reason,p_details:details,p_affected_student_id:role==="parent"&&childId?childId:null}); if(error){setMessage(error.message);setSaving(false);return;} setMessage("Report submitted. Examify administrators will review it."); setSaving(false); setTimeout(()=>router.back(),1200);}
 if(!person)return <main className="min-h-screen px-4 py-8"><div className="mx-auto max-w-2xl">Loading report form...</div></main>;
 const safetyReason=["harassment","bullying","safety"].includes(reason);
 return <main className="min-h-screen px-4 py-8 text-slate-900"><div className="mx-auto max-w-2xl"><button onClick={()=>router.back()} className="text-sm font-semibold text-[#2563EB]">← Back</button><div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-red-600">Safety report</p><h1 className="mt-1 text-3xl font-bold">Report {person.display_name}</h1><p className="mt-2 text-sm text-slate-600">Reports go to Examify administrators. Teacher reports are also shared with institutions the teacher belongs to. Student harassment/safety reports can alert linked parents and institutions.</p><form onSubmit={submit} className="mt-6 space-y-5"><label className="block text-sm font-semibold">Reason<select value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"><option value="harassment">Harassment</option><option value="bullying">Bullying</option><option value="inappropriate">Inappropriate behavior</option><option value="safety">Safety concern</option><option value="impersonation">Impersonation</option><option value="spam">Spam</option><option value="other">Other</option></select></label>{role==="parent"&&safetyReason&&children.length>0&&<label className="block text-sm font-semibold">Affected child (optional)<select value={childId} onChange={e=>setChildId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"><option value="">Not about one of my children</option>{children.map(c=><option key={c.student_id} value={c.student_id}>{c.student_name}</option>)}</select><span className="mt-1 block text-xs font-normal text-slate-500">If selected, that child's linked institution(s) will also receive the safety report.</span></label>} {role==="student"&&safetyReason&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Because this is a harassment/bullying/safety report from a student account, your linked parent/guardian and accepted institution(s) will receive a safety copy.</div>}<label className="block text-sm font-semibold">What happened?<textarea required minLength={10} maxLength={2000} rows={7} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Describe what happened, when it happened, and anything an administrator should know." className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"/></label><button disabled={saving} className="w-full rounded-xl bg-red-600 px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Submitting...":"Submit report"}</button>{message&&<p className="text-sm text-slate-700">{message}</p>}</form></div></div></main>;
}
